* NasiA font

iAWriter Mono フォントの足りない文字を NasuM で補ったフォントです

視認性と大人っぽい雰囲気をいい感じに両立しているなと思います

* ビルド

ヒンティングに =fontforge= 組み込みの機能を使う方法と、 =ttfautohint=
という外部ツールを使う方法があります。 =ttfautohint= の方が高速でやや
クオリティも高い気がするので、自分はそちらを使っています。

** 生成方法 (=ttfautohint= を使う場合, 推奨)：

1. =fontforge=, =ttfautohint= をインストール

   Mac の場合は Homebrew で入ります。

   : brew install fontforge ttfautohint

   Windows の場合は手動で公式からインストーラをダウンロードしてインス
   トール＆ PATH を通すか、 Bash on Windows から =apt-get= でも入ると
   思います (試せていないので、ごめんなさい)。

2. iA Writer Mono をダウンロード

   iA Writer Mono を公式からダウンロードして、
   =iAWriterMonoS-Regular.ttf= を =fonts= ディレクトリにコピーします。

3. NasuM をダウンロード

   NasuM を公式からダウンロードして、 =NasuM-Regular-20141215.ttf= を
   =fonts= ディレクトリにコピーします。

5. スクリプトを実行

   : make

   成功すると =dist= ディレクトリに =nasia-Medium.ttf= (と =tmp= に中
   間生成物 ... こちらは削除しても構いません) が生成されます。

** 生成方法 (=ttfautohint= を使わない場合)：

上の生成方法のステップ 5 (=make=) の前に =Makefile= の先頭から４行のコ
メントアウトを編集して、 =HINTER= に =fontforge= を設定します。

ステップ 1 での =ttfautohint= のインストールは不要です。

* アップデート

フォントに更新があった場合、新しいフォントをインストールする前に古いフォ
ントの情報を削除しないと反映されません。

1. インストール済みのフォントを削除

   Mac の場合は =Font Book= アプリケーションから削除できました。

2. フォントキャッシュをクリア

   Mac の場合は

   : sudo atsutil databases -remove

   でできました (パスワードを訊かれます)。最近はその後、フォントキャッ
   シュの再構築に再起動が必要なようです。
